[package]
name = "scsl_cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "scsl"
path = "src/main.rs"

[dependencies]
scsl_core = { path = "../scsl_core" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
